<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Admin\Roles\Services\" />
    <Folder Include="Features\Dashboard\Services\" />
    <Folder Include="Features\Tracker\PatientWorkflow\Services\" />
    <Folder Include="Features\Tracker\ReferralIntake\Models\" />
    <Folder Include="Features\Tracker\ReferralIntake\Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
  </ItemGroup>

</Project>
