using MediatR;

namespace CCAP.Application.Features.Referrals.Commands.CreateReferralIntake;

public sealed record CreateReferralIntakeCommand(
    string MRN,
    string FirstName,
    string MiddleName,
    string LastName,
    DateOnly? DateOfBirth,
    string? Gender,
    string? PrimaryPhone,
    string? AlternatePhone,
    string? StreetAddress,
    string? City,
    string? State,
    string? ZipCode,
    string? EmergencyContactName,
    string? EmergencyContactRelationship,
    string? EmergencyContactPhone,
    string ReferralNumber,
    DateTime ReferralDate,
    string? ReferralSource,
    string? Priority,
    string? PrimaryInsurance,
    string? InsuranceMemberId,
    bool AuthorizationRequired,
    string? ReferringPhysician,
    string? PhysicianPhone,
    string? PrimaryDiagnosis,
    string? SecondaryDiagnosis,
    IReadOnlyCollection<string> OrderedServices,
    string? ReferralNotes,
    Guid? CoordinatorId,
    Guid? ClinicianId,
    Guid? DisciplineId,
    DateOnly? SocDate,
    string? VisitPriority,
    string? CaseStatus,
    string? InternalNotes,
    Stream PdfStream,
    string PdfFileName,
    string PdfContentType) : IRequest<CreateReferralIntakeResult>;